[package]
name = "canvas-node"
version = "0.1.0"
authors = ["Canvas"]
edition = "2018"

[dependencies]
canvas-runtime = { version = "0.1.0", path = "../runtime" }

[[bin]]
name = "canvas"
path = "src/main.rs"
