on:
  pull_request:
  release:
    types: [ created ]

jobs:
  get-rust-versions:
    runs-on: ubuntu-latest
    container:
      image: paritytech/ci-linux:production
    steps:
      - name: Checkout sources & submodules
        uses: actions/checkout@master
        with:
          fetch-depth: 1
          submodules: recursive

      - name: Rust Cache
        uses: Swatinem/rust-cache@v1.2.0

      - run: cargo build --release --bins